/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package client;

import java.io.IOException;

import org.apache.http.HttpEntity;
import org.apache.http.HttpResponse;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.util.EntityUtils;

import client.util.Auth;
public class App {

    private static final String BASE_URL = System.getenv("BEANHUB_API_URL");
    private static Auth Authentication =  new Auth(System.getenv("BEANHUB_CLIENT_ID"));

    public static void main(String[] args) {
        System.out.println("Base URL: " + BASE_URL);
        try {
            Authentication.GetCode();
        } catch (IOException e) {
            throw new RuntimeException(e);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }

    }


}
