/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package client;

import java.io.IOException;

import client.util.PostRecipe;
import org.apache.http.HttpEntity;
import org.apache.http.HttpResponse;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.util.EntityUtils;

import client.util.Auth;
public class App {

    private static final String BASE_URL = System.getenv("BEANHUB_API_URL");
    private static Auth Authentication =  new Auth(System.getenv("BEANHUB_CLIENT_ID"));

   private static final PostRecipe postRecipe = new PostRecipe("Adrian");

    public static void main(String[] args) throws IOException, InterruptedException {
        // System.out.println(BASE_URL);
        // System.out.println(Authentication.GetCode());
       System.out.println(postRecipe.construct());
//        System.out.println();
//        try {
//            Authentication.GetCode();
//        } catch (IOException e) {
//            throw new RuntimeException(e);
//        } catch (InterruptedException e) {
//            throw new RuntimeException(e);
//        }

    }


}
