name: Java CI with Gradle
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build_api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 

    # This is wack AF, WTF
    - name: Inject application.yml
      run: |
        cd Beanhub.API
        echo "spring:" > ./Beanhub.API/src/main/resources/application.yml
        echo "  datasource:" >> ./Beanhub.API/src/main/resources/application.yml
        echo "    url: ${{ secrets.DB_BUILD_URL }}" >> ./Beanhub.API/src/main/resources/application.yml
        echo "    username: ${{ secrets.DB_BUILD_USERNAME }}" >> ./Beanhub.API/src/main/resources/application.yml
        echo "    password: ${{ secrets.DB_BUILD_PASSWORD }}" >> /./Beanhub.API/src/main/resourcesapplication.yml
        echo "    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver" >> ./Beanhub.API/src/main/resources/application.yml


    - name: Build with Gradle Wrapper
      run: |
        cd BeanHub.API
        ./gradlew
        ./gradlew build